{% set name = "pika" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: pika-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/p/pika/pika-{{ version }}.tar.gz
  sha256: 84aa6d0cf60bbdb79d5780544a4a4e1799392760127bf9de2a03d3c3b92f5f1a

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv '

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools

  run:
    - python >=3.6

test:
  imports:
    - pika

about:
  home: https://pika.readthedocs.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Pure Python RabbitMQ/AMQP 0-9-1 client library
  doc_url: https://pika.readthedocs.io
  dev_url: https://github.com/pika/pika

extra:
  recipe-maintainers:
    - ltalirz
    - chrisjsewell
