{% set version = "1.0.0b1" %}

package:
  name: pika
  version: {{ version }}

source:
  fn: pika-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/pika/pika-{{ version }}.tar.gz
  sha256: 922fc08918a782420c27bab7868ea359de4dad565ab505f0a85c1945a862041c

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - pika

about:
  home: http://pika.readthedocs.org
  license: BSD 3-clause
  summary: Pure Python RabbitMQ/AMQP 0-9-1 client library

extra:
  recipe-maintainers:
    - frol
