{% set version = "0.11.2" %}

package:
  name: pika
  version: {{ version }}

source:
  fn: pika-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/pika/pika-{{ version }}.tar.gz
  sha256: ded1cf12810f909099a3a698cc5adf495b73fd2da1d8f669f8b267664653122d

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - pika

about:
  home: http://pika.readthedocs.org
  license: BSD 3-clause
  summary: Pure Python RabbitMQ/AMQP 0-9-1 client library

extra:
  recipe-maintainers:
    - frol
