{% set name = "pika" %}
{% set version = "1.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: pika-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/p/pika/pika-{{ version }}.tar.gz
  sha256: 48d1f50297e76be4fc798fd5232d4d532d7a4758e51f7c0ae6c4004b9808a26b

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv '

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools

  run:
    - python >=3.6

test:
  imports:
    - pika

about:
  home: https://pika.readthedocs.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Pure Python RabbitMQ/AMQP 0-9-1 client library
  doc_url: https://pika.readthedocs.io
  dev_url: https://github.com/pika/pika

extra:
  recipe-maintainers:
    - ltalirz
    - chrisjsewell
