# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: beta-xcode6.1

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "gk16JzqiKiFqaBhDU80KVW3DZajbTlVA1Ao4oMsEPxnCXTl4RRBCgpJkekoEgwFnmFSB0wNTsWhORo3KjgwKqT+OyTNTkPI5zz8ezQ0QVnMYqqXI1RRNGCzfMfrLX6OlsqETyDANqUa9E4cC2xm8peabk60FZgwZISLPff2CNmCEO9mESJe7JxsWSDs+J7TGKuuJFwM8arTUwJJyXyoE1IEoIOuzCoF8uuR9pjCpG6RQo7fTgXFb6Rg5eW7o+TewmzSbGMqCUzrTRftugXefviIDuSc4GrLyDuwx/1h/BOpqeSWuBuaZ1eN3hb2ey1EbPMILchBOCjCzW5qkcUEfVahGD9ESEV8XV+F2CkXKopWNE2VOSL4Uvylc8nADT/WZ8d7UIy5EZjkw0o6pf4Mfm/3h7Ybx/9iiWZeH1U6/eFS+3ATGkPkZqdbiSdgsn8gSqAF05gSSTk7KBTC4TTGOxr7f+onXMUcj5unhwDmHOO2fa9APnRvLA644MIIjYcnoZUta+AYAqJWSmlICsPSIkqBqoUOfD6aABWPoPmIuCHHw2QaCyBGqGxj1twmtH4ivphkGs1r5jCGhhpwZAUGa1gkVhRZplr4m04vYU1RfxHZtk2eNNcwl776KWqznl1gDEq/hChwhL1TeDdw628Uf55jOIzSvW8ADmW+jjEP8c3c="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
